routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Crypt;
use Illuminate\Contracts\Encryption\DecryptException;
use Illuminate\Support\Facades\DB;
use App\Bkd;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::group(['middleware' => ['auth.logout']], function () {
    Route::get('login','Auth\LoginController@showLoginForm');
    Route::post('login','Auth\LoginController@login')->name('login'); 
    Route::get('lupapassword','Auth\LoginController@lupapassword')->name('lupa.password');
    Route::post('checkemail','Auth\LoginController@prosescekemail')->name('cek.email');
    Route::get('updatepassword/{token}','Auth\LoginController@updatepassword')->name('update.password');
    Route::post('updatepassword','Auth\LoginController@prosesupdatepassword')->name('proses.updatepassword');
});
// Route::post('forgot-password','LoginController@forgotPassword')->name('forgotpassword');

Route::get('logout','Auth\LoginController@logout')->name('logout');
// Auth::routes();
Route::group(['middleware' => ['auth.custom']], function () {
    Route::get('/','DashboardController@index')->name('dashboard');    
    Route::resource('bkd','BKDController');
    Route::resource('mahasiswa','MahasiswaController');
    Route::resource('dosen','DosenController');
    Route::resource('matakuliah','MataKuliahController');
    Route::resource('dosen','DosenController');
    Route::resource('regis-admin','RegistrasiAdminController');
    Route::resource('jabatan','JabatanController');
    Route::resource('jabatan-pegawai','JabatanPegawaiController');
    Route::resource('sesi','SesiController');
    Route::resource('ruangan', 'RuanganController');
    Route::resource('jadwal', 'JadwalController');
    Route::get('resetuuiddosen/{id}','DosenController@resetuuid');
    Route::post('jabatan-pegawai-admin','JabatanPegawaiController@jabatanadmin')->name('jabatan-pegawai-admin.store');
    Route::get('hasiljadwal/{id}','GenerateJadwalController@result')->name('testing_ya');
    Route::get('/program-studi','BKDController@programstudi')->name('programstudi');
    Route::get('/dosen-prodi/{id}','BKDController@dosenprodi');
    Route::get('/kelas-prodi/{id}/{semester}','BKDController@kelasprodi');
    Route::get('/data-matakuliah','MataKuliahController@datamatakuliah');
    Route::get('/bkd-matkul/{prodi}/{semester}','BKDController@bkdmatkul');
    Route::get('/editbkd','BKDController@dataeditbkd')->name('editbkd');
    Route::get('/data-jabatan','JabatanController@getdata')->name('data-jabatan');
    Route::get('/testcekdosen/{id}','BKDController@dosenprodi');
    Route::post('/filter-bkd','BKDExportController@filtertampilan')->name('filter-bkd');
    Route::post('/bkd-export-pdf','BKDExportController@exportpdf')->name('export-bkd');  
    Route::get('generate','GenerateJadwalController@index')->name('generate.index');   
    Route::post('cek','JadwalController@cek')->name('cekjadwal');   
    Route::get('pindahjadwal','PindahController@pindahjadwal')->name('pindahjadwal');   
    Route::post('ceksemua','JadwalController@ceksemua')->name('ceksemua');   
    Route::post('generate','GenerateJadwalController@generateJadwal')->name('generate.post');    
    Route::post('cekgenerate','GenerateJadwalController@cekgenerate')->name('cekgenerate');    
    Route::get('cekhari/{hari}','GenerateJadwalController@cekhari')->name('cekhari');
    Route::post('filterlab','CekController@editcek')->name('filterlab');
    // Route::get('filterlab','CekController@editcek')->name('filterlab');

    Route::get('kelas-test','TestController@kelas');
    Route::get('testdulu','TestController@index')->name("test.cek");
    Route::post('hari-sesi','TestController@harisesi')->name("harisesi");    
    
    Route::post('tambahjenis','CekController@tambahjenis')->name('tambahjenis');
    Route::post('perubahansesi','CekController@perubahansesi')->name('perubahansesi');
    Route::post('publish','CekController@publish')->name('publish');
    Route::post('gantipassword','Auth\LoginController@gantipassword')->name('gantipassword');   

    Route::post('datajadwal',"TestController@jadwalsemua")->name('datajadwal');
    Route::get('setcolor',"SetColorController@set")->name('setcolor');
    Route::post('setcolor',"SetColorController@setPost")->name('setcolor.post');
    Route::post('updatesetcolor/{id}',"SetColorController@setUpdate")->name('setcolor.update');

    Route::post('pindahjadwalpost','PindahController@pindah')->name('pindah');
    Route::post('updatepindah','PindahController@updatepindah')->name('updatepindah');
    Route::get('delete-color/{id}','SetColorController@hapus')->name('hapuscolor');
    Route::get('absensi','AbsensiController@index')->name('absensi');
    Route::get('absensi/{kelas}','AbsensiController@rekap')->name('rekapabsensi');
    Route::get('rekap','AbsensiController@rekap');
    Route::post('gantiruangan','PindahController@gantiruangan')->name('gantiruangan');
    Route::post('harirequest','PindahController@harirequest')->name('harirequest');
    Route::post('updateruangan','PindahController@updateruangan')->name('updateruangan');    
    Route::post('exportjadwal','JadwalController@export')->name('export.jadwal');    
});

app/Http/Controllers/JabatanController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\DataJabatan;
use App\DataJabatanPegawai;
use Carbon\Carbon;
use DB;
class JabatanController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //     
        // $adminjurusan = DataJabatanPegawai::with(['jabatan','admin_pegawai'])->where('deleted_at',NULL)->get();
        // $dosenjurusan = DataJabatanPegawai::with(['jabatan','dosen_pegawai'])->where('deleted_at',NULL)->get();
        $adminjurusan = DB::connection('presensi')->table('detail_jabatan_pegawai')
                            ->join('admin_jurusan','admin_jurusan.kode_admin_jurusan','detail_jabatan_pegawai.id_pegawai')
                            ->join('data_jabatan','data_jabatan.id','detail_jabatan_pegawai.id_jabatan')
                            ->where('detail_jabatan_pegawai.deleted_at',NULL)
                            ->get();
        $dosenjurusan = DB::connection('presensi')->table('polindra_presensi.detail_jabatan_pegawai')
                            ->join('polindra_siakad_v1_db.dosen','polindra_siakad_v1_db.dosen.user_id','polindra_presensi.detail_jabatan_pegawai.id_pegawai')
                            ->join('polindra_presensi.data_jabatan','polindra_presensi.detail_jabatan_pegawai.id_jabatan','polindra_presensi.data_jabatan.id')
                            ->where('polindra_presensi.detail_jabatan_pegawai.deleted_at',NULL)
                            ->get();
        // dd($dosenjurusan);
        $no=1;
        $n=1;
        $jabatan = DataJabatan::paginate(2);  
        return view('contents.jabatan.index',compact('jabatan','adminjurusan','no','dosenjurusan','n'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $jabatan = ucfirst($request->jabatan);
        $cek = DataJabatan::where('jabatan',$jabatan)->first();
        if ($cek) {
            return response()->json([
                'status'=>false,
                'message'=>'Data Sudah ada'
            ]);
        }else{
            $insert = new DataJabatan;
            $insert->jabatan = $jabatan;
            $insert->created_at=Carbon::now('Asia/Jakarta');
            $insert->save();        
            return response()->json([
                'status'=>true,
                'message'=>"Data Berhasil di simpan",    
                'jabatan'=>$insert
            ]);
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $data = DataJabatan::find($id);
        return response()->json($data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        $update = DataJabatan::find($id);
        $update->jabatan=ucfirst($request->jabatan);
        $update->save();

        return redirect(route('jabatan.index'))->with('success','Data Berhasil di Update');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $cek = DataJabatanPegawai::where('id_jabatan',$id)->where('deleted_at',NULL)->count();
        if ($cek>0) {            
            return response()->json([
                'status'=>true,
                'message'=>"Tidak dapat menghapus, Data sudah dipakai"
            ]);
        }else{
            $hapus = DataJabatan::find($id);
            $hapus->delete();
            return response()->json([
                'status'=>false,
                'message'=>"Data Berhasil di Hapus, Silahkan masukan data lagi"
            ]);
        }
    }    
}

resources/views/contents/jabatan/index.blade.php
@extends('master')
@section('title','Master Data Jabatan')    
@section('content')
<div class="content mt-3">
    @if ($message = Session::get('success'))
        <div class="alert alert-success alert-block">
                <button type="button" class="close" data-dismiss="alert">×</button> 
            <strong>{{ $message }}</strong>
        </div>
    @endif
    <div id="message">

    </div>
    <div class="animated fadeIn">
        <div class="row"> 
            @if (strtolower(Session::get('jabatan'))=="admin jurusan"
                    ||strtolower(Session::get('jabatan'))=="admin")
                @include('permissions.adminjurusan.pendataanjabatan')
            @endif
            @if (strtolower(Session::get('jabatan'))=="0")
                @include('permissions.adminsiakad.masterjabatan')
                @include('permissions.adminsiakad.pendataanjabatan')
            @endif            
        </div>
    </div>
</div>
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
    <div class="modal-content">
        <form id="formedit" method="post">
            @csrf
            @method('PUT')
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Edit Jabatan</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                    <div class="modal-body" id="editmodal">
                        
                    </div>
                <div class="modal-footer">
                <button type="submit" class="btn btn-success">Update</button>
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </form>
    </div>
    </div>
</div>
@push('script')
<script src="{{asset('assets/js/axios.min.js')}}"></script>
<script src="{{asset('vendors/jquery/dist/jquery.min.js')}}"></script>
<script src="{{asset('assets/js/sweetalert2.js')}}"></script>
<script>    
    $('#jabatanpost').on('submit',function(event){
        event.preventDefault();                
        var jabatan = $('#jbtn').val();        
        axios.post(`{{route('jabatan.store')}}`, {
            _token:"{{csrf_token()}}",
            jabatan:jabatan,
        })
        .then(function (response) {
            if (response.data.status==false) {                    
                var message = `
                <div class="alert alert-danger alert-block">
                    <button type="button" class="close" data-dismiss="alert">×</button>                         
                    ${response.data.message}
                </div>
                `;
                $('#message').html(message);
            }else{
                var message = `
                <div class="alert alert-success alert-block">
                    <button type="button" class="close" data-dismiss="alert">×</button>                         
                    ${response.data.message}
                </div>
                `;
                $('#message').html(message);                    
                var html = `
                    <tr>
                        <td>${response.data.jabatan.jabatan}</td>
                        <td align="center">
                            <a href="#edit" data-idedit="${response.data.jabatan.id}" data-toggle="modal" data-target="#exampleModal" class="btn btn-sm btn-warning" title="Edit"><i class="fa fa-edit"></i></a>
                            <a href="#delete" data-id="${response.data.jabatan.id}" class="btn btn-sm btn-danger" title="Hapus"><i class="fa fa-trash"></i></a>
                        </td>
                    </tr>
                    {{$jabatan->links()}}
                `;            
                $('#jabatan').append(html);
            }
        }).catch(function (error) {
            console.log(error);
        });        
    });

    $(document).on('click','a[href="#delete"]',function(){
        var dataId=$(this).data('id');        
        Swal.fire({
                title: 'Peringatan',
                text: `Apa kamu yakin untuk Menghapusnya ?`,
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Hapus'
                }).then((result) => {
                    if (result.value) {  
                        axios.delete(`jabatan/${dataId}`,{_token:"{{csrf_token()}}"}).then((res)=>{
                            console.log(res.data);
                            if(res.data.status===false){
                                Swal.fire({
                                    title:'Sukses',
                                    text:res.data.message,
                                    icon:'success',
                                }).then(()=>{
                                    window.location.href="{{route('jabatan.index')}}";
                                });                                
                            }else{
                                Swal.fire({
                                    title:'Peringatan',
                                    text:res.data.message,
                                    icon:'error',
                                });   
                            }
                        }).catch((error)=>{
                            console.log(error);
                        });                                       
                    }
                })
    });
</script>
<script>
    $(document).on('click','a[href="#editjabatan"]',function(){        
        var dataIdedit=$(this).data('idedit');
        axios.get(`jabatan/${dataIdedit}/edit`,{_token:"{{csrf_token()}}"}).then((res)=>{            
            console.log(res);
            var html = `
                <input type="text" name="jabatan" id="jbtn" class="form-control" value="${res.data.jabatan}" placeholder="Masukan jabatan">                                
            `;
            $('#editmodal').html(html);
            var action = '{{ route("jabatan.update", ":dataId") }}';
            action = action.replace(':dataId', dataIdedit);
            $('#formedit').attr('action',action);
            // var message = `
            //     <div class="alert alert-success alert-block">
            //         <button type="button" class="close" data-dismiss="alert">×</button>                         
            //         ${response.data.message}
            //     </div>
            //     `;
            // $('#message').html(message); 
        }).catch((error)=>{
            console.log(error);
        });
    });
</script>
<script>
    $(document).on('click','a[href="#hapusjabatandosen"]',function(){
        var dataId=$(this).data('id');
        console.log(dataId);
        Swal.fire({
                title: 'Peringatan',
                text: `Apa kamu yakin untuk Menghapusnya ?`,
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Hapus'
        }).then((result) => {
            if (result.value) {  
                axios.delete(`jabatan-pegawai/${dataId}`,{_token:"{{csrf_token()}}"}).then((res)=>{
                    console.log(res.data);                            
                        Swal.fire({
                            title:'Sukses',
                            text:res.data.message,
                            icon:'success',
                        }).then(()=>{
                            window.location.href="{{route('jabatan.index')}}";
                        });                                                            
                }).catch((error)=>{
                    console.log(error);
                });                                       
            }
        });
    });
</script>
<script>
    $(document).on('click','a[href="#hapusjabatanadmin"]',function(){
        var dataId=$(this).data('id');
        console.log(dataId);
        Swal.fire({
                title: 'Peringatan',
                text: `Apa kamu yakin untuk Menghapusnya ?`,
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Hapus'
                }).then((result) => {
                    if (result.value) {  
                        axios.delete(`regis-admin/${dataId}`,{_token:"{{csrf_token()}}"}).then((res)=>{
                            console.log(res.data);                            
                                Swal.fire({
                                    title:'Sukses',
                                    text:res.data.message,
                                    icon:'success',
                                }).then(()=>{
                                    window.location.href="{{route('jabatan.index')}}";
                                });                                                            
                        }).catch((error)=>{
                            console.log(error);
                        });                                       
                    }
        });
    });
</script>   
@endpush
@endsection