routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Crypt;
use Illuminate\Contracts\Encryption\DecryptException;
use Illuminate\Support\Facades\DB;
use App\Bkd;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::group(['middleware' => ['auth.logout']], function () {
    Route::get('login','Auth\LoginController@showLoginForm');
    Route::post('login','Auth\LoginController@login')->name('login'); 
    Route::get('lupapassword','Auth\LoginController@lupapassword')->name('lupa.password');
    Route::post('checkemail','Auth\LoginController@prosescekemail')->name('cek.email');
    Route::get('updatepassword/{token}','Auth\LoginController@updatepassword')->name('update.password');
    Route::post('updatepassword','Auth\LoginController@prosesupdatepassword')->name('proses.updatepassword');
});
// Route::post('forgot-password','LoginController@forgotPassword')->name('forgotpassword');

Route::get('logout','Auth\LoginController@logout')->name('logout');
// Auth::routes();
Route::group(['middleware' => ['auth.custom']], function () {
    Route::get('/','DashboardController@index')->name('dashboard');    
    Route::resource('bkd','BKDController');
    Route::resource('mahasiswa','MahasiswaController');
    Route::resource('dosen','DosenController');
    Route::resource('matakuliah','MataKuliahController');
    Route::resource('dosen','DosenController');
    Route::resource('regis-admin','RegistrasiAdminController');
    Route::resource('jabatan','JabatanController');
    Route::resource('jabatan-pegawai','JabatanPegawaiController');
    Route::resource('sesi','SesiController');
    Route::resource('ruangan', 'RuanganController');
    Route::resource('jadwal', 'JadwalController');
    Route::get('resetuuiddosen/{id}','DosenController@resetuuid');
    Route::post('jabatan-pegawai-admin','JabatanPegawaiController@jabatanadmin')->name('jabatan-pegawai-admin.store');
    Route::get('hasiljadwal/{id}','GenerateJadwalController@result')->name('testing_ya');
    Route::get('/program-studi','BKDController@programstudi')->name('programstudi');
    Route::get('/dosen-prodi/{id}','BKDController@dosenprodi');
    Route::get('/kelas-prodi/{id}/{semester}','BKDController@kelasprodi');
    Route::get('/data-matakuliah','MataKuliahController@datamatakuliah');
    Route::get('/bkd-matkul/{prodi}/{semester}','BKDController@bkdmatkul');
    Route::get('/editbkd','BKDController@dataeditbkd')->name('editbkd');
    Route::get('/data-jabatan','JabatanController@getdata')->name('data-jabatan');
    Route::get('/testcekdosen/{id}','BKDController@dosenprodi');
    Route::post('/filter-bkd','BKDExportController@filtertampilan')->name('filter-bkd');
    Route::post('/bkd-export-pdf','BKDExportController@exportpdf')->name('export-bkd');  
    Route::get('generate','GenerateJadwalController@index')->name('generate.index');   
    Route::post('cek','JadwalController@cek')->name('cekjadwal');   
    Route::get('pindahjadwal','PindahController@pindahjadwal')->name('pindahjadwal');   
    Route::post('ceksemua','JadwalController@ceksemua')->name('ceksemua');   
    Route::post('generate','GenerateJadwalController@generateJadwal')->name('generate.post');    
    Route::post('cekgenerate','GenerateJadwalController@cekgenerate')->name('cekgenerate');    
    Route::get('cekhari/{hari}','GenerateJadwalController@cekhari')->name('cekhari');
    Route::post('filterlab','CekController@editcek')->name('filterlab');
    // Route::get('filterlab','CekController@editcek')->name('filterlab');

    Route::get('kelas-test','TestController@kelas');
    Route::get('testdulu','TestController@index')->name("test.cek");
    Route::post('hari-sesi','TestController@harisesi')->name("harisesi");    
    
    Route::post('tambahjenis','CekController@tambahjenis')->name('tambahjenis');
    Route::post('perubahansesi','CekController@perubahansesi')->name('perubahansesi');
    Route::post('publish','CekController@publish')->name('publish');
    Route::post('gantipassword','Auth\LoginController@gantipassword')->name('gantipassword');   

    Route::post('datajadwal',"TestController@jadwalsemua")->name('datajadwal');
    Route::get('setcolor',"SetColorController@set")->name('setcolor');
    Route::post('setcolor',"SetColorController@setPost")->name('setcolor.post');
    Route::post('updatesetcolor/{id}',"SetColorController@setUpdate")->name('setcolor.update');

    Route::post('pindahjadwalpost','PindahController@pindah')->name('pindah');
    Route::post('updatepindah','PindahController@updatepindah')->name('updatepindah');
    Route::get('delete-color/{id}','SetColorController@hapus')->name('hapuscolor');
    Route::get('absensi','AbsensiController@index')->name('absensi');
    Route::get('absensi/{kelas}','AbsensiController@rekap')->name('rekapabsensi');
    Route::get('rekap','AbsensiController@rekap');
    Route::post('gantiruangan','PindahController@gantiruangan')->name('gantiruangan');
    Route::post('harirequest','PindahController@harirequest')->name('harirequest');
    Route::post('updateruangan','PindahController@updateruangan')->name('updateruangan');    
    Route::post('exportjadwal','JadwalController@export')->name('export.jadwal');    
});

app/Bkd.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Bkd extends Model
{
    //
    protected $connection = 'presensi';
    protected $table = 'bkd';
    protected $guarded = [];
    // protected $primaryKey = 'kode_bkd';

    public function matkul(){
        return $this->hasOne(MataKuliah::class,'kode_matkul','kode_matkul');
    }
}

app/Http/Controllers/BKDController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use DB;
use Carbon\Carbon;
use Session;
class BKDController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $bkd = DB::connection('presensi')->table('bkd')->join('polindra_siakad_v1_db.dosen','polindra_siakad_v1_db.dosen.dosen_kode','bkd.dosen_kode')
                ->select('bkd.*','polindra_siakad_v1_db.dosen.dosen_nama','polindra_siakad_v1_db.dosen.dosen_kode','polindra_siakad_v1_db.dosen.dosen_gelar_depan','polindra_siakad_v1_db.dosen.dosen_gelar_belakang','polindra_siakad_v1_db.data_kelas.*','mata_kuliah.*')
                ->join('polindra_siakad_v1_db.data_kelas','polindra_siakad_v1_db.data_kelas.kelas_kode','bkd.kode_kelas')
                ->join('mata_kuliah','mata_kuliah.kode_matkul','bkd.kode_matkul')
                ->where('status_bkd','Aktif')
                ->where('jurusan',Session::get('jurusan'))
                ->orderBy('bkd.updated_at','desc')
                ->get();   
        $tahun_ajaran = DB::connection('presensi')->table('bkd')->where('status_bkd','Aktif')->groupBy('tahun_ajaran')->get();                
        return view('contents.bkd.index',compact('bkd','tahun_ajaran'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //       
        $jurusan = DB::connection('siakad')->table('program_jurusan')->where('jurusan_kode',Session::get('jurusan'))->get();
        $program_studi = DB::connection('siakad')->table('program_studi')->where('jurusan_kode',Session::get('jurusan'))->get();
        $semester = DB::connection('presensi')->table('mata_kuliah')->where('semester','<>','NULL')->groupBy('semester')->get();
        return view('contents.bkd.create',compact('jurusan','semester','program_studi'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //           
        $tahun_ajaran = $request->awal."/".$request->akhir;                     
        $request->validate([
            'prodi'=>'required',
            'dosenprodi'=>'required',
            'matkul'=>'required',
            'kelas'=>'required',
            'semester'=>'required',
            'sks_praktek'=>'required',
            'sks_teori'=>'required'
        ],[
            'required'=>':attribute Tidak Boleh Kosong'
        ]); 
        if ($request->semester%2==0) {
            $jenis = "ganjil";
            $ganjil = [1,3,5,7];
            $genap = [2,4,6,8];
            $get = DB::connection('presensi')->table('bkd')
                   ->where('jurusan',Session::get('jurusan'))
                   ->whereIn('semester',$genap)
                   ->first();
            if ($get) {             
                if($get->tahun_ajaran!=$tahun_ajaran){
                    $cek = DB::connection('presensi')->table('bkd')
                        ->where('jurusan',Session::get('jurusan'))
                        ->whereRaw('LOWER(`status_bkd`)="aktif"')
                        ->where('tahun_ajaran',"<>",$tahun_ajaran)
                        ->whereIn('semester',$genap)
                        ->update([
                            'status_bkd'=>"Tidak Aktif"
                            ]);    
                }
            }else{
            $cek = DB::connection('presensi')->table('bkd')
                  ->where('jurusan',Session::get('jurusan'))
                  ->whereRaw('LOWER(`status_bkd`)="aktif"')
                //   ->where('tahun_ajaran',"<>",$tahun_ajaran)
                  ->whereIn('semester',$ganjil)
                  ->update([
                      'status_bkd'=>"Tidak Aktif"
                  ]);  
            }
        }else{
            $jenis = "genap";
            $ganjil = [1,3,5,7];
            $genap = [2,4,6,8];
            $get = DB::connection('presensi')->table('bkd')
                   ->where('jurusan',Session::get('jurusan'))
                   ->whereIn('semester',$ganjil)
                   ->first();
            if ($get) {             
                if($get->tahun_ajaran!=$tahun_ajaran){
                    $cek = DB::connection('presensi')->table('bkd')
                    ->where('jurusan',Session::get('jurusan'))
                    ->whereRaw('LOWER(`status_bkd`)="aktif"')
                    ->where('tahun_ajaran',"<>",$tahun_ajaran)
                    ->whereIn('semester',$ganjil)
                    ->update([
                        'status_bkd'=>"Tidak Aktif"
                    ]);    
                }
            }else{
            $cek = DB::connection('presensi')->table('bkd')
                  ->where('jurusan',Session::get('jurusan'))
                  ->whereRaw('LOWER(`status_bkd`)="aktif"')
                //   ->where('tahun_ajaran',"<>",$tahun_ajaran)
                  ->whereIn('semester',$genap)
                  ->update([
                      'status_bkd'=>"Tidak Aktif"
                  ]);                
            }
        }                   
        return $this->simpanData($request);
    }

    private function simpanData($request){
        $tahun_ajaran = $request->awal."/".$request->akhir;
        $total_sks = $request->sks_praktek+$request->sks_teori;       
        $kode_bkd ="BKD".Carbon::today('Asia/Jakarta')->format('Ymd').rand(1200,9999);        
        DB::connection('presensi')->table('bkd')->insert([
            'kode_bkd'=>$kode_bkd,
            'kode_kelas'=>$request->kelas,
            'tahun_ajaran'=>$tahun_ajaran,
            'dosen_kode'=>$request->dosenprodi,
            'kode_matkul'=>$request->matkul,
            'semester'=>$request->semester,
            'jumlah_sks_teori'=>$request->sks_teori,
            'jumlah_sks_praktek'=>$request->sks_praktek,
            'total_sks'=>$total_sks,
            'status_bkd'=>'Aktif',
            'jurusan'=>$request->prodi,
            'created_at'=>Carbon::now('Asia/Jakarta'),
            'updated_at'=>Carbon::now('Asia/Jakarta')
        ]);
        return redirect()->route('bkd.index')->with('success','Data Berhasil ditambahkan');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $ambil_jurusan = DB::connection('presensi')->table('bkd')->where('kode_bkd',$id)->first();
        $program_studi = DB::connection('siakad')->table('program_studi')->where('jurusan_kode',Session::get('jurusan'))->get();
        $semester = DB::connection('presensi')->table('mata_kuliah')->where('semester','<>','NULL')->groupBy('semester')->get();        
        $bkd = DB::connection('presensi')->table('polindra_presensi.bkd')
                ->join('polindra_siakad_v1_db.data_kelas','polindra_siakad_v1_db.data_kelas.kelas_kode','bkd.kode_kelas')
                ->join('polindra_siakad_v1_db.dosen','polindra_siakad_v1_db.dosen.dosen_kode','polindra_presensi.bkd.dosen_kode')
                ->join('polindra_presensi.mata_kuliah','polindra_presensi.mata_kuliah.kode_matkul','polindra_presensi.bkd.kode_matkul')
                ->join('polindra_siakad_v1_db.program_jurusan','polindra_siakad_v1_db.program_jurusan.jurusan_kode','polindra_presensi.bkd.jurusan')
                ->where('polindra_siakad_v1_db.program_jurusan.jurusan_kode',$ambil_jurusan->jurusan)
                ->where('polindra_presensi.bkd.kode_bkd',$id)
                ->first();        
        $tahunajaran=explode("/",$bkd->tahun_ajaran);
        return view('contents.bkd.edit',compact('bkd','tahunajaran','program_studi','semester'));   
        // dd($bkd);
    }    

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        $tahun_ajaran = $request->awal."/".$request->akhir;
        $total_sks = $request->sks_praktek+$request->sks_teori; 
        $update = DB::connection('presensi')->table('bkd')->where('kode_bkd',$id)->update([            
            'kode_kelas'=>$request->kelas,
            'tahun_ajaran'=>$tahun_ajaran,
            'dosen_kode'=>$request->dosenprodi,
            'kode_matkul'=>$request->matkul,
            'semester'=>$request->semester,
            'jumlah_sks_teori'=>$request->sks_teori,
            'jumlah_sks_praktek'=>$request->sks_praktek,
            'total_sks'=>$total_sks,            
            'updated_at'=>Carbon::now('Asia/Jakarta')
        ]);
        return redirect()->route('bkd.index')->with('success','Data Berhasil di update');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        DB::connection('presensi')->table('bkd')->where('kode_bkd',$id)->delete();
        return response()->json([
            'status'=>true,
            'code'=>200,
            'message'=>"Data Berhasil di Hapus",
        ]);
    }
    public function programstudi(){
        $programstudi = DB::connection('siakad')->table('data_kelas')->get('program_studi_kode')->groupBy('program_studi_kode');        
        return response()->json([
            'status'=>true,
            'code'=>200,
            'message'=>"Data berhasil di ambil",
            'data'=>$programstudi
        ]);
    }
    public function dosenprodi($id){   
        $dosen = DB::connection('siakad')

resources/views/contents/bkd/create.blade.php
@extends('master')
@section('title','Create Beban Kinerja Dosen')    
@section('content')
<div class="content mt-3">
    <div class="animated fadeIn">
        <div class="row">
            <div class="col-md-12">
                @if (count($errors) > 0)
                    <div class="alert alert-danger alert-block">
                        <button type="button" class="close" data-dismiss="alert">×</button>                         
                            @foreach ($errors->all() as $error)
                                {{ $error }} <br>
                            @endforeach
                    </div>
                @endif
                <form action="{{route('bkd.store')}}" method="post" enctype="multipart/form-data" class="form-horizontal">   
                    @csrf                         
                    <div class="card">
                    <div class="card-header">
                        <strong>BKD</strong> Form Input
                    </div>
                        <div class="card-body card-block">
                            <div class="row form-group">
                                <div class="col col-md-3"><label for="text-input" class=" form-control-label">Pilih Jurusan</label></div>
                                <div class="col-12 col-md-9">
                                    <select name="prodi" id="programstudi" class="form-control">
                                        <option value="0" disabled="true" selected="true">Pilih</option>
                                        @foreach ($program_studi as $ps)
                                            <option value="{{$ps->program_studi_kode}}">{{$ps->program_studi_nama}}</option>
                                        @endforeach
                                        {{-- @foreach ($jurusan as $jr)
                                            <option value="{{$jr->jurusan_kode}}">{{$jr->jurusan_nama}}</option>
                                        @endforeach --}}
                                    </select>
                                </div>
                            </div>
                            <div class="row form-group">
                                <div class="col col-md-3"><label for="email-input" class=" form-control-label">Semester</label></div>
                                <div class="col-12 col-md-9">
                                    <select name="semester" id="semester" class="form-control">
                                        <option value="0" disabled="true" selected="true">Pilih</option>
                                        @foreach ($semester as $s)
                                            <option value="{{$s->semester}}">{{$s->semester}}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                            <div class="row form-group" id="dosenprodi">
                                <div class="col col-md-3"><label for="text-input" class=" form-control-label">Dosen</label></div>
                                <div class="col-12 col-md-9">
                                    <select name="dosenprodi" id="datadosenprodi" class="form-control">
                                        
                                    </select>
                                </div>
                            </div>
                            <div class="row form-group" id="datamatakuliah">
                                <div class="col col-md-3"><label for="text-input" class=" form-control-label">Mata Kuliah</label></div>
                                <div class="col-12 col-md-9">
                                    <select name="matkul" id="datamatkul" class="form-control">                                                                             
                                    </select>
                                </div>
                            </div>
                            <div class="row form-group" id="kelas">
                                <div class="col col-md-3"><label for="text-input" class=" form-control-label">Kelas </label></div>
                                <div class="col-12 col-md-9">
                                    <select name="kelas" id="datakelas" class="form-control">                                        
                                    </select>
                                </div>
                            </div>                            
                            <div class="row form-group">
                                <div class="col col-md-3"><label for="email-input" class=" form-control-label">Tahun Ajaran</label></div>
                                <div class="col-4 col-md-3"><input type="number" name="awal" placeholder="Tahun Ajaran" min="2000"  class="form-control"></div>                                
                                /
                                <div class="col-4 col-md-3"><input type="number" name="akhir" placeholder="Tahun Ajaran" min="2000" class="form-control"></div>
                            </div>
                            <div class="row form-group">
                                <div class="col col-md-3"><label for="password-input" class=" form-control-label">SKS Praktek</label></div>
                                <div class="col-12 col-md-9"><input type="number" name="sks_praktek" placeholder="SKS Praktek" min="0" max="20" class="form-control"></div>
                            </div>                            
                            <div class="row form-group">
                                <div class="col col-md-3"><label for="textarea-input" class=" form-control-label">SKS Teori</label></div>
                                <div class="col-12 col-md-9"><input type="number" name="sks_teori" placeholder="SKS Teori" min="0" max="20" class="form-control"></div>
                            </div>                                
                        </div>
                        <div class="card-footer">
                            <button type="submit" class="btn btn-success btn-sm">
                                <i class="fa fa-dot-circle-o"></i> Simpan
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>            
    </div>
</div>
@push('script')
    <script src="{{asset('assets/js/axios.min.js')}}"></script>
    <script src="{{asset('vendors/jquery/dist/jquery.min.js')}}"></script>
    <script src="{{asset('assets/js/sweetalert2.js')}}"></script>
    <script src="{{asset('assets/js/select2.min.js')}}"></script>
    <script>
        $('#datadosenprodi').select2({
            width:'resolve',
        });
        $('#datakelas').select2({
            width:'resolve',
        });
        $('#datamatkul').select2({
            width:'resolve',
        });
    </script>
    <script>
        $('#dosenprodi').hide();
        $('#kelas').hide();
        $('#datamatakuliah').hide();                            
            $('#programstudi').on('change',function(){
                // alert(this.value);
                $('#datadosenprodi').html(`<option value="0" disabled="true" selected="true">Pilih</option>`);
                $('#datakelas').html(`<option value="0" disabled="true" selected="true">Pilih</option>`);
                $('#datamatkul').html(`<option value="0" disabled="true" selected="true">Pilih</option>`);
                axios.get(`/dosen-prodi/${this.value}`).then((response)=>{                 
                    var data = response.data.dosen;
                    var panjang = response.data.dosen.length;                    
                    $('#datadosenprodi').children('option:not(:first)').remove();
                    for (let index = 0; index < panjang ; index++) {                        
                        $('#datadosenprodi').append(`                    
                            <option value="${data[index].dosen_kode}">${data[index].dosen_gelar_depan} ${data[index].dosen_nama}, ${data[index].dosen_gelar_belakang}</option>
                        `);
                    }
                    var panjang_data = response.data.dosen_luar.length;
                    var data_luar = response.data.dosen_luar;
                    for (let index = 0; index <panjang_data; index++) {                        
                           $('#datadosenprodi').append(`
                                <option value="${data_luar[index].dosen_kode}">${data_luar[index].dosen_gelar_depan} ${data_luar[index].dosen_nama}, ${data_luar[index].dosen_gelar_belakang}</option>
                           `)                     
                    }
                    $('#dosenprodi').show();
                }); 
                $('#datamatakuliah').show();                 
                var prodi = this.value;
                matkul(prodi);   
                $('#kelas').show();                              
            });

            function matkul(prodi) {                
                $('#semester').on('change',function(){
                    var semester = this.value;                                        
                    console.log(semester);
                    axios.get(`/bkd-matkul/${prodi}/${semester}`).then((response)=>{
                        var panjang = response.data.matkul.length;
                        var data = response.data.matkul;
                        $('#datamatkul').children('option:not(:first)').remove();
                        for (let index = 0; index < panjang; index++) {
                            $('#datamatkul').append(`
                                <option value="${data[index].kode_matkul}">${data[index].nama_matkul} (${data[index].program_studi})</option>
                            `);
                        }                    
                    });                       

                    axios.get(`/kelas-prodi/${prodi}/${semester}`).then((response)=>{
                        console.log(response.data);
                        var data = response.data.kelas;
                        var panjang = response.data.kelas.length;
                        $('#datakelas').children('option:not(:first)').remove();
                        for (let index = 0; index < panjang ; index++) {   
                            var cek = data[index].kelas_kode.split('18');
                            if (cek.length!=2) {
                                $('#datakelas').append(`                    
                                    <option value="${data[index].kelas_kode}">${data[index].kelas_nama}</option>
                                `);                                                           
                            }                                                    
                        }                        
                    });                  
                });
            }
    </script>
@endpush
@endsection