routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Crypt;
use Illuminate\Contracts\Encryption\DecryptException;
use Illuminate\Support\Facades\DB;
use App\Bkd;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::group(['middleware' => ['auth.logout']], function () {
    Route::get('login','Auth\LoginController@showLoginForm');
    Route::post('login','Auth\LoginController@login')->name('login'); 
    Route::get('lupapassword','Auth\LoginController@lupapassword')->name('lupa.password');
    Route::post('checkemail','Auth\LoginController@prosescekemail')->name('cek.email');
    Route::get('updatepassword/{token}','Auth\LoginController@updatepassword')->name('update.password');
    Route::post('updatepassword','Auth\LoginController@prosesupdatepassword')->name('proses.updatepassword');
});
// Route::post('forgot-password','LoginController@forgotPassword')->name('forgotpassword');

Route::get('logout','Auth\LoginController@logout')->name('logout');
// Auth::routes();
Route::group(['middleware' => ['auth.custom']], function () {
    Route::get('/','DashboardController@index')->name('dashboard');    
    Route::resource('bkd','BKDController');
    Route::resource('mahasiswa','MahasiswaController');
    Route::resource('dosen','DosenController');
    Route::resource('matakuliah','MataKuliahController');
    Route::resource('dosen','DosenController');
    Route::resource('regis-admin','RegistrasiAdminController');
    Route::resource('jabatan','JabatanController');
    Route::resource('jabatan-pegawai','JabatanPegawaiController');
    Route::resource('sesi','SesiController');
    Route::resource('ruangan', 'RuanganController');
    Route::resource('jadwal', 'JadwalController');
    Route::get('resetuuiddosen/{id}','DosenController@resetuuid');
    Route::post('jabatan-pegawai-admin','JabatanPegawaiController@jabatanadmin')->name('jabatan-pegawai-admin.store');
    Route::get('hasiljadwal/{id}','GenerateJadwalController@result')->name('testing_ya');
    Route::get('/program-studi','BKDController@programstudi')->name('programstudi');
    Route::get('/dosen-prodi/{id}','BKDController@dosenprodi');
    Route::get('/kelas-prodi/{id}/{semester}','BKDController@kelasprodi');
    Route::get('/data-matakuliah','MataKuliahController@datamatakuliah');
    Route::get('/bkd-matkul/{prodi}/{semester}','BKDController@bkdmatkul');
    Route::get('/editbkd','BKDController@dataeditbkd')->name('editbkd');
    Route::get('/data-jabatan','JabatanController@getdata')->name('data-jabatan');
    Route::get('/testcekdosen/{id}','BKDController@dosenprodi');
    Route::post('/filter-bkd','BKDExportController@filtertampilan')->name('filter-bkd');
    Route::post('/bkd-export-pdf','BKDExportController@exportpdf')->name('export-bkd');  
    Route::get('generate','GenerateJadwalController@index')->name('generate.index');   
    Route::post('cek','JadwalController@cek')->name('cekjadwal');   
    Route::get('pindahjadwal','PindahController@pindahjadwal')->name('pindahjadwal');   
    Route::post('ceksemua','JadwalController@ceksemua')->name('ceksemua');   
    Route::post('generate','GenerateJadwalController@generateJadwal')->name('generate.post');    
    Route::post('cekgenerate','GenerateJadwalController@cekgenerate')->name('cekgenerate');    
    Route::get('cekhari/{hari}','GenerateJadwalController@cekhari')->name('cekhari');
    Route::post('filterlab','CekController@editcek')->name('filterlab');
    // Route::get('filterlab','CekController@editcek')->name('filterlab');

    Route::get('kelas-test','TestController@kelas');
    Route::get('testdulu','TestController@index')->name("test.cek");
    Route::post('hari-sesi','TestController@harisesi')->name("harisesi");    
    
    Route::post('tambahjenis','CekController@tambahjenis')->name('tambahjenis');
    Route::post('perubahansesi','CekController@perubahansesi')->name('perubahansesi');
    Route::post('publish','CekController@publish')->name('publish');
    Route::post('gantipassword','Auth\LoginController@gantipassword')->name('gantipassword');   

    Route::post('datajadwal',"TestController@jadwalsemua")->name('datajadwal');
    Route::get('setcolor',"SetColorController@set")->name('setcolor');
    Route::post('setcolor',"SetColorController@setPost")->name('setcolor.post');
    Route::post('updatesetcolor/{id}',"SetColorController@setUpdate")->name('setcolor.update');

    Route::post('pindahjadwalpost','PindahController@pindah')->name('pindah');
    Route::post('updatepindah','PindahController@updatepindah')->name('updatepindah');
    Route::get('delete-color/{id}','SetColorController@hapus')->name('hapuscolor');
    Route::get('absensi','AbsensiController@index')->name('absensi');
    Route::get('absensi/{kelas}','AbsensiController@rekap')->name('rekapabsensi');
    Route::get('rekap','AbsensiController@rekap');
    Route::post('gantiruangan','PindahController@gantiruangan')->name('gantiruangan');
    Route::post('harirequest','PindahController@harirequest')->name('harirequest');
    Route::post('updateruangan','PindahController@updateruangan')->name('updateruangan');    
    Route::post('exportjadwal','JadwalController@export')->name('export.jadwal');    
});

resources/views/permissions/sekertarisjurusan/dashboard.blade.php
@extends('master')
@section('title','Dashboard')
@section('content')
<div class="breadcrumbs">
    <div class="col-sm-4">
        <div class="page-header float-left">
            <div class="page-title">
                <h1>Dashboard</h1>
            </div>
        </div>
    </div>
    <div class="col-sm-8">
        <div class="page-header float-right">
            <div class="page-title">
                <ol class="breadcrumb text-right">
                    <li class="active">Dashboard</li>
                </ol>
            </div>
        </div>
    </div>
</div>

    <div class="content mt-3">        
        <!--/.col-->
        <div class="col-sm-6 col-lg-4">
            <div class="card text-white bg-flat-color-2">
                <div class="card-body pb-0">                    
                    <h4 class="mb-0">
                        
                    </h4>
                    <p class="text-light">Mahasiswa Jurusan {{Session::get('jurusan')}}</p>

                    <div class="chart-wrapper px-0" style="height:70px;" height="70">
                        <h1 class="count">{{count($tot)}}</h1>                        
                    </div>

                </div>
            </div>
        </div>        
        <!--/.col-->

        <div class="col-sm-6 col-lg-4">
            <div class="card text-white bg-flat-color-3">
                <div class="card-body pb-0">                   
                    <h4 class="mb-0">
                        
                    </h4>
                    <p class="text-light">Semester</p>

                </div>

                <div class="chart-wrapper px-0" style="height:70px;" height="70">                    
                    <h1> &nbsp;{{strtoupper($semester)}}</h1>
                </div>
            </div>
        </div>
        <!--/.col-->

        <div class="col-sm-6 col-lg-4">
            <div class="card text-white bg-flat-color-4">
                <div class="card-body pb-0">                    
                    <h4 class="mb-0">
                        
                    </h4>
                    <p class="text-light">Total BKD {{strtoupper($semester)}}</p>

                    <div class="chart-wrapper px-3" style="height:70px;" height="70">
                        <h1 class="count">{{count($totbkd)}}</h1>            
                    </div>

                </div>
            </div>
        </div>

        <div class="col-sm-6 col-lg-4 col-md-4">
            <div class="card text-white bg-flat-color-5">
                <div class="card-body pb-0">                    
                    <h4 class="mb-0">
                        
                    </h4>
                    <p class="text-light">Total Dosen</p>

                    <div class="" style="height:70px;" height="70">
                        <h1 class="count">{{count($dosen)}}</h1>
                    </div>

                </div>
            </div>
        </div>
        <!--/.col-->    

        <div class="col-sm-6 col-lg-4 col-md-4">
            <div class="card text-white bg-flat-color-1">
                <div class="card-body pb-0">                    
                    <h4 class="mb-0">
                        
                    </h4>
                    <p class="text-light">Total Kelas</p>

                    <div class="" style="height:70px;" height="70">
                        <h1 class="count">{{count($kelas)}}</h1>              
                    </div>

                </div>
            </div>
        </div>
        <!--/.col-->  

        <div class="col-sm-6 col-lg-4 col-md-4">
            <div class="card text-white bg-flat-color-3">
                <div class="card-body pb-0">                    
                    <h4 class="mb-0">
                        
                    </h4>
                    <p class="text-light">Total Ruangan yang terpakai</p>

                    <div class="" style="height:70px;" height="70">
                        <h1 class="count">{{count($ruangan)}}</h1>              
                    </div>

                </div>
            </div>
        </div>
        <!--/.col-->  
</div> 
@endsection

resources/views/permissions/sekertarisjurusan/menu.blade.php
<li class="active">
    <a href="{{route('dashboard')}}"> <i class="menu-icon fa fa-dashboard"></i>Dashboard </a>
</li>
<h3 class="menu-title">General</h3><!-- /.menu-title -->
<li>
    <a href="{{route('jadwal.index')}}"><i class="menu-icon fa fa-calendar"></i> Jadwal</a>
</li>
<li class="menu-item-has-children dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="menu-icon fa fa-edit"></i> BKD</a>
    <ul class="sub-menu children dropdown-menu">
        <li><i class="menu-icon fa fa-plus"></i><a href="{{route('bkd.create')}}"> Create BKD</a></li>
        <li><i class="menu-icon fa fa-eye"></i><a href="{{route('bkd.index')}}">Lihat BKD</a></li>        
    </ul>
</li>
<li>
    <a href="{{route('setcolor')}}"><i class="menu-icon fa fa-cog"></i> Set Color</a></li>
</li>