routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Crypt;
use Illuminate\Contracts\Encryption\DecryptException;
use Illuminate\Support\Facades\DB;
use App\Bkd;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::group(['middleware' => ['auth.logout']], function () {
    Route::get('login','Auth\LoginController@showLoginForm');
    Route::post('login','Auth\LoginController@login')->name('login'); 
    Route::get('lupapassword','Auth\LoginController@lupapassword')->name('lupa.password');
    Route::post('checkemail','Auth\LoginController@prosescekemail')->name('cek.email');
    Route::get('updatepassword/{token}','Auth\LoginController@updatepassword')->name('update.password');
    Route::post('updatepassword','Auth\LoginController@prosesupdatepassword')->name('proses.updatepassword');
});
// Route::post('forgot-password','LoginController@forgotPassword')->name('forgotpassword');

Route::get('logout','Auth\LoginController@logout')->name('logout');
// Auth::routes();
Route::group(['middleware' => ['auth.custom']], function () {
    Route::get('/','DashboardController@index')->name('dashboard');    
    Route::resource('bkd','BKDController');
    Route::resource('mahasiswa','MahasiswaController');
    Route::resource('dosen','DosenController');
    Route::resource('matakuliah','MataKuliahController');
    Route::resource('dosen','DosenController');
    Route::resource('regis-admin','RegistrasiAdminController');
    Route::resource('jabatan','JabatanController');
    Route::resource('jabatan-pegawai','JabatanPegawaiController');
    Route::resource('sesi','SesiController');
    Route::resource('ruangan', 'RuanganController');
    Route::resource('jadwal', 'JadwalController');
    Route::get('resetuuiddosen/{id}','DosenController@resetuuid');
    Route::post('jabatan-pegawai-admin','JabatanPegawaiController@jabatanadmin')->name('jabatan-pegawai-admin.store');
    Route::get('hasiljadwal/{id}','GenerateJadwalController@result')->name('testing_ya');
    Route::get('/program-studi','BKDController@programstudi')->name('programstudi');
    Route::get('/dosen-prodi/{id}','BKDController@dosenprodi');
    Route::get('/kelas-prodi/{id}/{semester}','BKDController@kelasprodi');
    Route::get('/data-matakuliah','MataKuliahController@datamatakuliah');
    Route::get('/bkd-matkul/{prodi}/{semester}','BKDController@bkdmatkul');
    Route::get('/editbkd','BKDController@dataeditbkd')->name('editbkd');
    Route::get('/data-jabatan','JabatanController@getdata')->name('data-jabatan');
    Route::get('/testcekdosen/{id}','BKDController@dosenprodi');
    Route::post('/filter-bkd','BKDExportController@filtertampilan')->name('filter-bkd');
    Route::post('/bkd-export-pdf','BKDExportController@exportpdf')->name('export-bkd');  
    Route::get('generate','GenerateJadwalController@index')->name('generate.index');   
    Route::post('cek','JadwalController@cek')->name('cekjadwal');   
    Route::get('pindahjadwal','PindahController@pindahjadwal')->name('pindahjadwal');   
    Route::post('ceksemua','JadwalController@ceksemua')->name('ceksemua');   
    Route::post('generate','GenerateJadwalController@generateJadwal')->name('generate.post');    
    Route::post('cekgenerate','GenerateJadwalController@cekgenerate')->name('cekgenerate');    
    Route::get('cekhari/{hari}','GenerateJadwalController@cekhari')->name('cekhari');
    Route::post('filterlab','CekController@editcek')->name('filterlab');
    // Route::get('filterlab','CekController@editcek')->name('filterlab');

    Route::get('kelas-test','TestController@kelas');
    Route::get('testdulu','TestController@index')->name("test.cek");
    Route::post('hari-sesi','TestController@harisesi')->name("harisesi");    
    
    Route::post('tambahjenis','CekController@tambahjenis')->name('tambahjenis');
    Route::post('perubahansesi','CekController@perubahansesi')->name('perubahansesi');
    Route::post('publish','CekController@publish')->name('publish');
    Route::post('gantipassword','Auth\LoginController@gantipassword')->name('gantipassword');   

    Route::post('datajadwal',"TestController@jadwalsemua")->name('datajadwal');
    Route::get('setcolor',"SetColorController@set")->name('setcolor');
    Route::post('setcolor',"SetColorController@setPost")->name('setcolor.post');
    Route::post('updatesetcolor/{id}',"SetColorController@setUpdate")->name('setcolor.update');

    Route::post('pindahjadwalpost','PindahController@pindah')->name('pindah');
    Route::post('updatepindah','PindahController@updatepindah')->name('updatepindah');
    Route::get('delete-color/{id}','SetColorController@hapus')->name('hapuscolor');
    Route::get('absensi','AbsensiController@index')->name('absensi');
    Route::get('absensi/{kelas}','AbsensiController@rekap')->name('rekapabsensi');
    Route::get('rekap','AbsensiController@rekap');
    Route::post('gantiruangan','PindahController@gantiruangan')->name('gantiruangan');
    Route::post('harirequest','PindahController@harirequest')->name('harirequest');
    Route::post('updateruangan','PindahController@updateruangan')->name('updateruangan');    
    Route::post('exportjadwal','JadwalController@export')->name('export.jadwal');    
});

resources/views/partial/head.blade.php
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>@yield('title')</title>
    <meta name="description" content="Sufee Admin - HTML5 Admin Template">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="apple-touch-icon" href="apple-icon.png">
    <link rel="shortcut icon" href="favicon.ico">
    {{-- <link rel="stylesheet" href="https://cdn.datatables.net/1.10.21/css/dataTables.jqueryui.min.css"> --}}
    {{-- <link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/timepicker/1.3.5/jquery.timepicker.min.css">     --}}
    <link rel="stylesheet" href="{{asset('assets/js/wickedpicker.min.css')}}">
    <link rel="stylesheet" href="{{asset('assets/css/gayaan.css')}}">
    <link rel="stylesheet" href="{{asset('vendors/bootstrap/dist/css/bootstrap.min.css')}}">
    <link rel="stylesheet" href="{{asset('vendors/font-awesome/css/font-awesome.min.css')}}">
    <link rel="stylesheet" href="{{asset('vendors/themify-icons/css/themify-icons.css')}}">
    <link rel="stylesheet" href="{{asset('vendors/flag-icon-css/css/flag-icon.min.css')}}">
    <link rel="stylesheet" href="{{asset('vendors/selectFX/css/cs-skin-elastic.css')}}">
    <link rel="stylesheet" href="{{asset('vendors/jqvmap/dist/jqvmap.min.css')}}">
	<link rel="stylesheet" href="{{asset('assets/css/style.css')}}">
	<link rel="stylesheet" href="{{asset('assets/css/jquery-ui.min.css')}}">
	<link rel="stylesheet" href="http://code.jquery.com/mobile/1.2.0/jquery.mobile-1.2.0.min.css" />       
	<link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-colorpicker/2.3.6/css/bootstrap-colorpicker.css" rel="stylesheet">
	
    {{-- <link rel="stylesheet" href="{{asset('vendors/datatables.net-bs4/css/dataTables.bootstrap4.min.css')}}"> --}}
    <link rel="stylesheet" href="{{asset('assets/css/simplePagination.css')}}">
    <link rel="stylesheet" href="{{asset('vendors/datatables.net-buttons-bs4/css/buttons.bootstrap4.min.css')}}">
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,600,700,800' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="{{asset('assets/css/select2.min.css')}}">
    {{-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.css"> --}}
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.21/css/dataTables.bootstrap4.min.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/responsive/2.2.5/css/responsive.bootstrap4.min.css">
    <style>           
    @import url(http://fonts.googleapis.com/css?family=Open+Sans:700);
.cssload-container * {
	color: rgb(0,0,0);    
	font-size: 33px;
	font-weight: 700;
	font-family: 'Open Sans', sans-serif;
}
.cssload-container {
    margin-top: 20%;
    margin-left: 5%;
	position: absolute;
	width: 117px;
	height: 49px;
	left: 50%;
	transform: translate(-50%, -50%);
		-o-transform: translate(-50%, -50%);
		-ms-transform: translate(-50%, -50%);
		-webkit-transform: translate(-50%, -50%);
		-moz-transform: translate(-50%, -50%);
}
.cssload-container > div {
	position: absolute;
	transform-origin: center;
		-o-transform-origin: center;
		-ms-transform-origin: center;
		-webkit-transform-origin: center;
		-moz-transform-origin: center;
}
.cssload-l {
	left: 8px;
}
.cssload-i {
	left: 85px;
}
.cssload-d {
	left: 60px;
}
.cssload-n {
	left: 95px;
}
.cssload-g {
	left: 120px;
}
.cssload-square,
.cssload-circle,
.cssload-triangle {
	left: 29px;
}
.cssload-square {
	background: rgb(117,179,209);
	width: 23px;
	height: 23px;
	left: 31px;
	top: 12px;
	transform: scale(0);
		-o-transform: scale(0);
		-ms-transform: scale(0);
		-webkit-transform: scale(0);
		-moz-transform: scale(0);
	animation: cssload-shrinkgrow 3.45s ease-in-out infinite;
		-o-animation: cssload-shrinkgrow 3.45s ease-in-out infinite;
		-ms-animation: cssload-shrinkgrow 3.45s ease-in-out infinite;
		-webkit-animation: cssload-shrinkgrow 3.45s ease-in-out infinite;
		-moz-animation: cssload-shrinkgrow 3.45s ease-in-out infinite;
	animation-delay: 2.3s;
		-o-animation-delay: 2.3s;
		-ms-animation-delay: 2.3s;
		-webkit-animation-delay: 2.3s;
		-moz-animation-delay: 2.3s;
}
.cssload-circle {
	background: rgb(129,212,125);
	width: 26px;
	height: 26px;
	top: 10px;
	left: 29px;
	border-radius: 50%;
	animation: cssload-shrinkgrow 3.45s ease-in-out infinite;
		-o-animation: cssload-shrinkgrow 3.45s ease-in-out infinite;
		-ms-animation: cssload-shrinkgrow 3.45s ease-in-out infinite;
		-webkit-animation: cssload-shrinkgrow 3.45s ease-in-out infinite;
		-moz-animation: cssload-shrinkgrow 3.45s ease-in-out infinite;
	animation-delay: 0s;
		-o-animation-delay: 0s;
		-ms-animation-delay: 0s;
		-webkit-animation-delay: 0s;
		-moz-animation-delay: 0s;
}
.cssload-triangle {
	width: 0;
	height: 0;
	left: 29px;
	top: 11px;
	border-style: solid;
	border-width: 0 14.5px 24.1px 14.5px;
	border-color: transparent transparent rgb(210,121,140) transparent;
	transform: scale(0);
		-o-transform: scale(0);
		-ms-transform: scale(0);
		-webkit-transform: scale(0);
		-moz-transform: scale(0);
	animation: cssload-shrinkgrow 3.45s ease-in-out infinite;
		-o-animation: cssload-shrinkgrow 3.45s ease-in-out infinite;
		-ms-animation: cssload-shrinkgrow 3.45s ease-in-out infinite;
		-webkit-animation: cssload-shrinkgrow 3.45s ease-in-out infinite;
		-moz-animation: cssload-shrinkgrow 3.45s ease-in-out infinite;
	animation-delay: 1.15s;
		-o-animation-delay: 1.15s;
		-ms-animation-delay: 1.15s;
		-webkit-animation-delay: 1.15s;
		-moz-animation-delay: 1.15s;
}


@keyframes cssload-shrinkgrow {
	0% {
		transform: scale(0);
	}
	12.5% {
		transform: scale(1);
	}
	25% {
		transform: scale(1);
	}
	33% {
		transform: scale(0);
	}
	100% {
		transform: scale(0);
	}
}

@-o-keyframes cssload-shrinkgrow {
	0% {
		-o-transform: scale(0);
	}
	12.5% {
		-o-transform: scale(1);
	}
	25% {
		-o-transform: scale(1);
	}
	33% {
		-o-transform: scale(0);
	}
	100% {
		-o-transform: scale(0);
	}
}

@-ms-keyframes cssload-shrinkgrow {
	0% {
		-ms-transform: scale(0);
	}
	12.5% {
		-ms-transform: scale(1);
	}
	25% {
		-ms-transform: scale(1);
	}
	33% {
		-ms-transform: scale(0);
	}
	100% {
		-ms-transform: scale(0);
	}
}

@-webkit-keyframes cssload-shrinkgrow {
	0% {
		-webkit-transform: scale(0);
	}
	12.5% {
		-webkit-transform: scale(1);
	}
	25% {
		-webkit-transform: scale(1);
	}
	33% {
		-webkit-transform: scale(0);
	}
	100% {
		-webkit-transform: scale(0);
	}
}

@-moz-keyframes cssload-shrinkgrow {
	0% {
		-moz-transform: scale(0);
	}
	12.5% {
		-moz-transform: scale(1);
	}
	25% {
		-moz-transform: scale(1);
	}
	33% {
		-moz-transform: scale(0);
	}
	100% {
		-moz-transform: scale(0);
	}
}
    </style>
</head>

resources/views/partial/header.blade.php
<header id="header" class="header">

            <div class="header-menu">

                <div class="col-sm-7">
                    <a id="menuToggle" class="menutoggle pull-left"><i class="fa fa fa-tasks"></i></a>
                    <div class="header-left"> 
                        <h2>Selamat Datang <small>{{Session::get('nama')}}</small></h2>                        
                    </div>
                </div>

                <div class="col-sm-5">             
                    <table class="float-right">
                        <tr align=right>
                            <td>
                                @if (strtolower(Session::get('jabatan'))=="0")

                                @else
                                    <a href="#gantipassword" title="Ganti Password" data-toggle="modal" data-target="#gantipassword">
                                        <img class="user-avatar" width="30px" src="{{asset('images/cp.png')}}" alt="User Avatar">                                                      
                                    </a>
                                @endif                                
                                {{-- <a class="nav-link" href="#" title="Ganti Password"><i class="fa fa-key"></i></a> --}}
                            </td>
                            <td><a href="#logout" title="Logout">
                                <img class="user-avatar rounded-circle" width="30px" src="{{asset('images/power.png')}}" alt="User Avatar">                                                      
                            </a></td>
                        </tr>
                    </table>                                            
                </div>
            </div>

        </header>
        <!-- Modal -->
<div class="modal fade" id="gantipassword" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">        
        <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Ganti Password</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="modal-body">            
            <label for="">New Password</label>  <br>
            <input type="password" name="new_password" id="new_pass" placeholder="New Password" class="form-control">
            <label for="">Confirm Password</label>
            <input type="password" name="confirm_password" id="confirm_pass" placeholder="Confirm Password" class="form-control">
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <button type="button" onclick="gantipassword()" class="btn btn-primary">Simpan</button>
        </div>
        </div>
    </div>
</div>
        <!-- /header -->
        <!-- Header-->
@push('script')
<script src="{{asset('assets/js/axios.min.js')}}"></script>
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>  
<script src="{{asset('assets/js/sweetalert2.js')}}"></script>   
<script>
    $(document).on('click','a[href="#logout"]',function(){
        Swal.fire({
            title: 'Peringatan',
            text: `Apakah Anda yakin untuk Logout ? `,
            icon: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#3085d6',
            cancelButtonColor: '#d33',
            confirmButtonText: 'Logout'
        }).then((result) => {
            if (result.value) {
                window.location.href="{{route('logout')}}";
            }
        });
    }); 
    
    function gantipassword(){
        var userid = "{{Session::get('user_id')}}";
        var newpass = $('#new_pass').val();              
        var confirmpass = $('#confirm_pass').val();
        if (newpass==confirmpass) {
            axios.post('gantipassword',{
                userid:userid,
                newpass:newpass,
            }).then((response)=>{
                Swal.fire({
                    title:'Sukses',
                    text:"Password berhasil diganti",
                    icon:'success',
                });
            });
        }else{
            Swal.fire({
                title:'Error',
                text:"Password dengan Konfirmasi Password Tidak Sama",
                icon:'error',
            });
        }
    }
</script> 
@endpush

resources/views/partial/script.blade.php
@stack('script')
<script src="{{asset('vendors/jquery/dist/jquery.min.js')}}"></script>
    <script src="{{asset('assets/js/init-scripts/data-table/datatables-init.js')}}"></script>
    <script src="{{asset('vendors/popper.js/dist/umd/popper.min.js')}}"></script>
    <script src="{{asset('vendors/bootstrap/dist/js/bootstrap.min.js')}}"></script>
    <script src="{{asset('assets/js/main.js')}}"></script>
    <script src="{{asset('vendors/chart.js/dist/Chart.bundle.min.js')}}"></script>
    <script src="{{asset('assets/js/dashboard.js')}}"></script>
    <script src="{{asset('assets/js/axios.min.js')}}"></script>
    <script src="{{asset('assets/js/widgets.js')}}"></script>
    <script src="{{asset('vendors/jqvmap/dist/jquery.vmap.min.js')}}"></script>
    <script src="{{asset('vendors/jqvmap/examples/js/jquery.vmap.sampledata.js')}}"></script>
    <script src="{{asset('vendors/jqvmap/dist/maps/jquery.vmap.world.js')}}"></script>
    <script>
        (function($) {
            "use strict";

            jQuery('#vmap').vectorMap({
                map: 'world_en',
                backgroundColor: null,
                color: '#ffffff',
                hoverOpacity: 0.7,
                selectedColor: '#1de9b6',
                enableZoom: true,
                showTooltip: true,
                values: sample_data,
                scaleColors: ['#1de9b6', '#03a9f5'],
                normalizeFunction: 'polynomial'
            });
        })(jQuery);
    </script>      
    {{-- https://code.jquery.com/jquery-3.5.1.js
    https://cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js
    https://cdn.datatables.net/1.10.21/js/dataTables.bootstrap4.min.js
    https://cdn.datatables.net/responsive/2.2.5/js/dataTables.responsive.min.js
    https://cdn.datatables.net/responsive/2.2.5/js/responsive.bootstrap4.min.js --}}
    <script src="https://code.jquery.com/jquery-3.5.1.js"></script>    
    <script src="https://cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js"></script>  
    <script src="https://cdn.datatables.net/1.10.21/js/dataTables.bootstrap4.min.js"></script>
    <script src="https://cdn.datatables.net/responsive/2.2.5/js/dataTables.responsive.min.js"></script>
    <script src="https://cdn.datatables.net/responsive/2.2.5/js/responsive.bootstrap4.min.js"></script>
    <script>
        $(document).ready(function() {
            $('#bootstrap-data-table-export').DataTable();
        });        
    </script>
    <script src="{{asset('vendors/datatables.net/js/jquery.dataTables.min.js')}}"></script>
    <script src="{{asset('vendors/datatables.net-bs4/js/dataTables.bootstrap4.min.js')}}"></script>
    <script src="{{asset('vendors/datatables.net-buttons/js/dataTables.buttons.min.js')}}"></script>
    <script src="{{asset('vendors/datatables.net-buttons-bs4/js/buttons.bootstrap4.min.js')}}"></script>
    <script src="{{asset('vendors/jszip/dist/jszip.min.js')}}"></script>
    <script src="{{asset('vendors/pdfmake/build/pdfmake.min.js')}}"></script>
    <script src="{{asset('vendors/pdfmake/build/vfs_fonts.js')}}"></script>
    <script src="{{asset('vendors/datatables.net-buttons/js/buttons.html5.min.js')}}"></script>
    <script src="{{asset('vendors/datatables.net-buttons/js/buttons.print.min.js')}}"></script>
    <script src="{{asset('vendors/datatables.net-buttons/js/buttons.colVis.min.js')}}"></script>    
    <script src="{{asset('assets/js/simplePagination.js')}}"></script>
    <script src="{{asset('assets/js/jquery-ui.min.js')}}"></script>

resources/views/partial/sidebar.blade.php
<!-- Left Panel -->
<aside id="left-panel" class="left-panel">
        <nav class="navbar navbar-expand-sm navbar-default">

            <div class="navbar-header">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#main-menu" aria-controls="main-menu" aria-expanded="false" aria-label="Toggle navigation">
                    <i class="fa fa-bars"></i>
                </button>
                <a class="navbar-brand" href="./">
                    {{-- <img src="images/logo.png" alt="Logo"> --}}
                </a>
                <a class="navbar-brand hidden" href="./">
                    {{-- <img src="images/logo2.png" alt="Logo"> --}}
                </a>
            </div>

            <div id="main-menu" class="main-menu collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    @if (strtolower(Session::get('jabatan'))=="sekertaris jurusan"
                         ||strtolower(Session::get('jabatan'))=="sekertaris"
                         ||strtolower(Session::get('jabatan'))=="sekjur"
                         ||strtolower(Session::get('jabatan'))=="sj")
                        @include('permissions.sekertarisjurusan.menu')
                    @endif
                    @if (strtolower(Session::get('jabatan'))=="admin jurusan"
                         ||strtolower(Session::get('jabatan'))=="admin")
                        @include('permissions.adminjurusan.menu')
                    @endif
                    @if (strtolower(Session::get('jabatan'))=="0")
                        @include('permissions.adminsiakad.menu')
                    @endif
                    {{-- <li class="active">
                        <a href="{{route('dashboard')}}"> <i class="menu-icon fa fa-dashboard"></i>Dashboard </a>
                    </li>
                    <h3 class="menu-title">General</h3><!-- /.menu-title -->
                    <li>
                        <a href="{{route('dosen.index')}}"> <i class="menu-icon fa fa-user"></i>Dosen</a>                        
                    </li>
                    <li>
                        <a href="{{route('mahasiswa.index')}}"> <i class="menu-icon fa fa-user"></i>Mahasiswa</a>                        
                    </li>
                    <li>
                        <a href=""><i class="menu-icon fa fa-calendar-o"></i> Absensi</a>
                    </li>
                    <h3 class="menu-title">Master Data</h3><!-- /.menu-title -->

                    <li>
                        <a href="{{route('jabatan.index')}}"> <i class="menu-icon fa fa-tasks"></i>Jabatan</a>                       
                    </li>
                    <li>
                        <a href="{{route('matakuliah.index')}}"> <i class="menu-icon fa fa-edit"></i>Mata Kuliah</a>                       
                    </li>                    
                    <h3 class="menu-title">Setting</h3><!-- /.menu-title -->
                    <li>
                        <a href="#"><i class="menu-icon fa fa-cog"></i> Pindah Jadwal</a>
                    </li>
                    <li>
                        <a href="#"><i class="menu-icon fa fa-cog"></i> Jam Ganti</a>
                    </li>
                    <li>
                        <a href="{{route('sesi.index')}}"><i class="menu-icon fa fa-cog"></i>Sesi</a>
                    </li> 
                    <li>
                        <a href="{{route('ruangan.index')}}"><i class="menu-icon fa fa-cog"></i>Ruangan</a>
                    </li> 
                    <li>
                        <a href="{{route('regis-admin.index')}}"><i class="menu-icon fa fa-cog"></i> Regis Admin Jurusan</a>
                    </li>                       --}}
                </ul>
            </div><!-- /.navbar-collapse -->
        </nav>
    </aside><!-- /#left-panel -->

    <!-- Left Panel -->